# Generated by Django 4.2.13 on 2025-01-12 14:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchesSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=555, null=True)),
                ('image', models.CharField(blank=True, max_length=555, null=True)),
                ('status', models.IntegerField()),
                ('sorting_params', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_At', null=True)),
            ],
            options={
                'db_table': 'batches_subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=555, null=True)),
                ('image', models.CharField(blank=True, max_length=555, null=True)),
                ('status', models.IntegerField()),
                ('sorting_params', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_At', null=True)),
            ],
            options={
                'db_table': 'chapters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_hin', models.TextField(blank=True, null=True)),
                ('question_eng', models.TextField(blank=True, null=True)),
                ('option1_hin', models.TextField(blank=True, null=True)),
                ('option1_eng', models.TextField(blank=True, null=True)),
                ('option2_hin', models.TextField(blank=True, null=True)),
                ('option2_eng', models.TextField(blank=True, null=True)),
                ('option3_hin', models.TextField(blank=True, null=True)),
                ('option3_eng', models.TextField(blank=True, null=True)),
                ('option4_hin', models.TextField(blank=True, null=True)),
                ('option4_eng', models.TextField(blank=True, null=True)),
                ('option5_hin', models.TextField(blank=True, null=True)),
                ('option5_eng', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('chapter', models.TextField(blank=True, null=True)),
                ('previous_of', models.CharField(blank=True, max_length=45, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('solution_hin', models.TextField(blank=True, null=True)),
                ('solution_eng', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=45, null=True)),
                ('section_type', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=45, null=True)),
                ('class_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'question_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret_key', models.CharField(max_length=20)),
                ('chapter', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('classes', models.CharField(blank=True, max_length=250, null=True)),
                ('questions_count', models.IntegerField(default=0)),
                ('promotion', tinymce.models.HTMLField(blank=True, null=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='quizzes', to='quiz.questionbank')),
            ],
            options={
                'db_table': 'quiz_quiz',
                'managed': True,
            },
        ),
    ]
